import { useEffect, useRef, useState } from 'react'
import { X, Plus, Trash2, ArrowUp, ArrowDown } from 'lucide-react'
import { api, type ApiTemplate } from '../api'
import { buildTemplate, groupButtons, variableKeys, type TemplateDraft, type TemplateKind, type ButtonDraft, type ButtonType, type HeaderType, type ParameterFormat, TemplateValidationError } from '../../shared/templates'
import { TEMPLATE_LANGUAGES } from '../../shared/template-languages'
import { draftFromTemplate, emptyDraft, unsupportedTemplateReason } from './drafts'
import { MediaPicker } from './MediaPicker'
import './templates.css'
import { TemplateFlowPicker } from '../flows/TemplateFlowPicker'

const buttonLabels: Record<ButtonType, string> = { QUICK_REPLY: 'Quick reply', URL: 'Visit website', PHONE_NUMBER: 'Call phone number', COPY_CODE: 'Copy coupon code', FLOW: 'Open WhatsApp Flow', CATALOG: 'View catalog', MPM: 'View items', SPM: 'View product' }
const kinds: [TemplateKind, string][] = [['STANDARD', 'Standard message'], ['CAROUSEL', 'Media carousel'], ['PRODUCT_CAROUSEL', 'Product carousel'], ['CATALOG', 'Catalog'], ['MPM', 'Multiple products'], ['SPM', 'Single product'], ['LIMITED_TIME_OFFER', 'Limited-time offer']]
const title = (s: string) => s.toLowerCase().replaceAll('_', ' ')
const fieldKey = (name: string) => name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^[^a-z]+|_+$/g, '')
const templateKey = (name: string) => name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')
const friendlyName = (name: string) => name.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
export function useDialog(close: () => void, busy: boolean) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    ref.current?.focus()
    return () => { document.body.style.overflow = previousOverflow; previous?.focus() }
  }, [])
  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape' && !busy) { e.stopPropagation(); close() }
    if (e.key !== 'Tab') return
    const nodes = [...(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), a[href]') || [])].filter(n => n.getClientRects().length > 0)
    if (!nodes.length) { e.preventDefault(); return }
    if (e.shiftKey && (document.activeElement === nodes[0] || document.activeElement === ref.current)) { nodes.at(-1)?.focus(); e.preventDefault() }
    if (!e.shiftKey && document.activeElement === nodes.at(-1)) { nodes[0].focus(); e.preventDefault() }
  }
  return { ref, onKeyDown }
}
function TextEditor({ label, value, examples, labels, format, max, onChange }: { label: string; value: string; examples: string[]; labels?: string[]; format: ParameterFormat; max: number; onChange: (text: string, examples: string[], labels: string[]) => void }) {
  const keys = variableKeys(value), [newName, setNewName] = useState('')
  const key = fieldKey(newName)
  const change = (next: string) => {
    const nextKeys = variableKeys(next)
    onChange(next, nextKeys.map(k => examples[keys.indexOf(k)] || ''), nextKeys.map(k => labels?.[keys.indexOf(k)] || (/^\d+$/.test(k) ? `Field ${k}` : k.replaceAll('_', ' '))))
  }
  const insertField = () => {
    const nextKey = format === 'NAMED' ? key : String(keys.length + 1)
    if (!nextKey || keys.includes(nextKey)) return
    const next = `${value}${value && !/\s$/.test(value) ? ' ' : ''}{{${nextKey}}}`
    const nextKeys = variableKeys(next)
    onChange(next, nextKeys.map(k => examples[keys.indexOf(k)] || ''), nextKeys.map(k => labels?.[keys.indexOf(k)] || (k === nextKey ? newName.trim() : /^\d+$/.test(k) ? `Field ${k}` : k.replaceAll('_', ' '))))
    setNewName('')
  }
  const removeField = (key: string) => change(value.replaceAll(`{{${key}}}`, '').replace(/ {2,}/g, ' ').trim())
  return <div className="template-text-editor">
    <label>{label}<textarea rows={4} value={value} onChange={e => change(e.target.value)} placeholder={format === 'NAMED' ? 'Hi {{first_name}}, your order is ready.' : 'Hi {{1}}, your order is ready.'} /></label>
    <small>{value.length}/{max} characters · {'Use *bold*, _italic_, ~strikethrough~ or ```monospace``` in the body.'}</small>
    {format === 'NAMED' ? <div className="template-inline"><label>Personalization field<input value={newName} onChange={e => setNewName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); insertField() } }} placeholder="Patient Name" /></label><button type="button" onClick={insertField} disabled={!key || keys.includes(key)}><Plus size={13} /> Add field</button></div> : <div className="template-inline"><small>Add a personalized value such as a name, date or reference.</small><button type="button" onClick={insertField}><Plus size={13} /> Add field</button></div>}
    {format === 'NAMED' && <small>Type a familiar label, such as “Patient Name.” It will be inserted as {'{{patient_name}}'}.</small>}
    {keys.length > 0 && <div className="template-examples"><small>Examples help Meta review your template. Actual values are supplied when sending.</small>{keys.map((key, i) => <div className="template-subcard" key={key}><div className="template-inline"><b>{labels?.[i] || friendlyName(key)}</b><button type="button" aria-label={`Remove ${labels?.[i] || friendlyName(key)} field`} onClick={() => removeField(key)}><Trash2 size={14} /> Remove field</button></div><div className="template-grid">{labels && <label>Field label<input value={labels[i] || ''} onChange={e => onChange(value, examples, keys.map((_, n) => n === i ? e.target.value : labels[n] || ''))} /></label>}<label>Example value<input value={examples[i] || ''} onChange={e => onChange(value, keys.map((_, n) => n === i ? e.target.value : examples[n] || ''), labels || [])} /></label></div></div>)}</div>}
  </div>
}
function ButtonEditor({ buttons, onChange, allowed, max = 10 }: { buttons: ButtonDraft[]; onChange: (buttons: ButtonDraft[]) => void; allowed: ButtonType[]; max?: number }) {
  const [type, setType] = useState<ButtonType>(allowed[0])
  const patch = (i: number, data: Partial<ButtonDraft>) => onChange(buttons.map((b, n) => n === i ? { ...b, ...data } : b))
  const move = (i: number, delta: number) => { const next = [...buttons]; [next[i], next[i + delta]] = [next[i + delta], next[i]]; onChange(next) }
  return <div><div className="template-inline"><label>Button type<select value={allowed.includes(type) ? type : allowed[0]} onChange={e => setType(e.target.value as ButtonType)}>{allowed.map(t => <option key={t} value={t}>{buttonLabels[t]}</option>)}</select></label><button type="button" disabled={buttons.length >= max} onClick={() => onChange([...buttons, { type: allowed.includes(type) ? type : allowed[0], text: type === 'SPM' ? 'View' : '', value: '', example: '', flowAction: 'navigate' }])}><Plus size={14} /> Add button</button></div>
    <small>Up to {max} buttons. Quick replies are grouped together in the delivered message.</small>
    {buttons.map((b, i) => <article className="template-subcard" key={i}><div className="template-inline"><b>{i + 1}. {buttonLabels[b.type]}</b><div className="template-button-tools"><button type="button" aria-label="Move button up" disabled={!i} onClick={() => move(i, -1)}><ArrowUp size={14} /></button><button type="button" aria-label="Move button down" disabled={i === buttons.length - 1} onClick={() => move(i, 1)}><ArrowDown size={14} /></button><button type="button" aria-label="Remove button" onClick={() => onChange(buttons.filter((_, n) => i !== n))}><Trash2 size={14} /></button></div></div>
      {!['COPY_CODE', 'SPM'].includes(b.type) && <label>Button label<input value={b.text} maxLength={25} onChange={e => patch(i, { text: e.target.value })} /></label>}
      {b.type === 'URL' && <><label>Website URL<input type="url" value={b.value || ''} onChange={e => patch(i, { value: e.target.value })} placeholder="https://example.com/orders/{{1}}" /></label><small>One optional variable, {'{{1}}'}, at the end of the URL.</small>{b.value?.includes('{{') && <label>Example URL suffix<input value={b.example || ''} onChange={e => patch(i, { example: e.target.value })} placeholder="order-123" /></label>}</>}
      {b.type === 'PHONE_NUMBER' && <label>International phone number<input type="tel" value={b.value || ''} onChange={e => patch(i, { value: e.target.value })} placeholder="+919876543210" /></label>}
      {b.type === 'COPY_CODE' && <label>Example coupon code<input maxLength={20} value={b.example || ''} onChange={e => patch(i, { example: e.target.value })} placeholder="WELCOME20" /></label>}
      {b.type === 'FLOW' && <TemplateFlowPicker value={b} change={change => patch(i, change)} />}
      {b.type === 'FLOW' && <><label>Flow reference<select value={b.flowJson !== undefined ? 'json' : b.flowName !== undefined ? 'name' : 'id'} onChange={e => { const mode = e.target.value; patch(i, { flowId: mode === 'id' ? '' : undefined, flowName: mode === 'name' ? '' : undefined, flowJson: mode === 'json' ? '' : undefined }) }}><option value="id">Published Flow ID</option><option value="name">Published Flow name</option><option value="json">Flow JSON</option></select></label>{b.flowJson !== undefined ? <label>Flow JSON<textarea rows={6} value={b.flowJson} onChange={e => patch(i, { flowJson: e.target.value })} /></label> : b.flowName !== undefined ? <label>Flow name<input value={b.flowName} onChange={e => patch(i, { flowName: e.target.value })} /></label> : <label>Flow ID<input value={b.flowId || ''} onChange={e => patch(i, { flowId: e.target.value })} /></label>}<label>Flow action<select value={b.flowAction || 'navigate'} onChange={e => patch(i, { flowAction: e.target.value as 'navigate' | 'data_exchange' })}><option value="navigate">Open a screen</option><option value="data_exchange">Exchange data with endpoint</option></select></label>{b.flowAction !== 'data_exchange' && <label>Screen ID<input value={b.navigateScreen || ''} onChange={e => patch(i, { navigateScreen: e.target.value })} /></label>}<small>The Flow token and initial data are supplied when sending.</small></>}
    </article>)}
  </div>
}
function renderExample(value: string, examples: string[]) { const keys = variableKeys(value); return value.replace(/\{\{([^{}]+)\}\}/g, (match, key) => examples[keys.indexOf(key)] || match) }
function Preview({ draft, headerPreview }: { draft: TemplateDraft; headerPreview: string }) {
  const auth = draft.category === 'AUTHENTICATION'
  return <aside className="template-preview"><small>WHATSAPP PREVIEW</small><div className="template-bubble">
    {!auth && draft.header?.type !== 'NONE' && !['CAROUSEL', 'PRODUCT_CAROUSEL'].includes(draft.kind || '') && <div className="template-preview-header">{headerPreview && draft.header?.type === 'IMAGE' ? <img src={headerPreview} alt="Header sample" /> : headerPreview && draft.header?.type === 'VIDEO' ? <video src={headerPreview} controls /> : draft.header?.type === 'TEXT' ? renderExample(draft.header.text || '', [draft.header.example || '']) : `${title(draft.header?.type || 'PRODUCT')} header`}</div>}
    {draft.kind === 'LIMITED_TIME_OFFER' && <b className="template-offer">{draft.limitedTimeOffer?.text || 'Offer title'}{draft.limitedTimeOffer?.hasExpiration && ' · Ends soon'}</b>}
    <p>{auth ? `123456 is your verification code.${draft.authentication?.addSecurityRecommendation ? ' For your security, do not share this code.' : ''}` : renderExample(draft.body, draft.examples) || 'Your message appears here.'}</p>
    {auth && draft.authentication?.codeExpirationMinutes && <small>This code expires in {draft.authentication.codeExpirationMinutes} minutes.</small>}
    {!auth && draft.footer && <small>{draft.footer}</small>}
    <div className="template-preview-buttons">{auth ? <span>{draft.authentication?.buttonText || 'Copy code'}</span> : ['CATALOG', 'MPM', 'SPM'].includes(draft.kind || '') ? <span>{buttonLabels[draft.kind as ButtonType]}</span> : groupButtons(draft.buttons).map((b, i) => <span key={i}>{b.type === 'COPY_CODE' ? 'Copy offer code' : b.text || buttonLabels[b.type]}</span>)}</div>
  </div>{['CAROUSEL', 'PRODUCT_CAROUSEL'].includes(draft.kind || '') && <div className="template-preview-carousel">{draft.carousel?.cards.map((card, i) => <div className="template-bubble" key={i}><div className="template-preview-header">{title(card.headerType)} · Card {i + 1}</div><p>{renderExample(card.body, card.examples)}</p><div className="template-preview-buttons">{groupButtons(card.buttons).map((b, n) => <span key={n}>{b.text || buttonLabels[b.type]}</span>)}</div></div>)}</div>}
    <small>Approximate preview. WhatsApp controls final styling and localized labels.</small>
  </aside>
}

export function TemplateModal({ close, created, template }: { close: () => void; created: (template: ApiTemplate) => void; template?: ApiTemplate }) {
  const [draft, setDraft] = useState<TemplateDraft>(() => template ? draftFromTemplate(template) : emptyDraft()), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false), [error, setError] = useState(''), [attempted, setAttempted] = useState(false), [draftNotice, setDraftNotice] = useState(''), [headerPreview, setHeaderPreview] = useState('')
  const [templateName, setTemplateName] = useState(() => template ? friendlyName(template.name) : ''), [headerFieldName, setHeaderFieldName] = useState('')
  const busy = saving || uploading, dialog = useDialog(close, busy), unsupported = unsupportedTemplateReason(template)
  const patch = (data: Partial<TemplateDraft>) => { if (data.kind || data.category || data.header?.type && data.header.type !== draft.header?.type) setHeaderPreview(''); setDraft(d => ({ ...d, ...data })); setError('') }
  const auth = draft.category === 'AUTHENTICATION', kind = draft.kind || 'STANDARD', format = draft.parameterFormat || 'POSITIONAL'
  const availableKinds = kinds.filter(([candidate]) => draft.category === 'MARKETING' || candidate === 'STANDARD')
  let validation = ''
  try { buildTemplate(draft) } catch (e) { validation = e instanceof TemplateValidationError ? `${e.field.replace(/carousel\.cards\.(\d+)/, (_, n) => `Card ${Number(n) + 1}`).replace(/buttons\.(\d+)/, (_, n) => `Button ${Number(n) + 1}`).replaceAll('.', ' ')}: ${e.message}` : 'Review the template fields' }
  const setKind = (kind: TemplateKind) => patch({ kind, header: { type: kind === 'SPM' ? 'PRODUCT' : 'NONE' }, footer: '', buttons: [], carousel: ['CAROUSEL', 'PRODUCT_CAROUSEL'].includes(kind) ? { cards: Array.from({ length: 2 }, () => ({ headerType: kind === 'PRODUCT_CAROUSEL' ? 'PRODUCT' : 'IMAGE', headerExample: '', body: '', examples: [], buttons: kind === 'PRODUCT_CAROUSEL' ? [{ type: 'SPM', text: 'View' }] : [] })) } : undefined, limitedTimeOffer: kind === 'LIMITED_TIME_OFFER' ? { text: '', hasExpiration: true } : undefined })
  const setCategory = (category: string) => {
    if (category === 'AUTHENTICATION') patch({ ...emptyDraft(), name: draft.name, language: draft.language, category, authentication: { otpType: 'COPY_CODE', addSecurityRecommendation: true, codeExpirationMinutes: 10, buttonText: 'Copy code', autofillText: 'Autofill' } })
    else patch({ category, kind: 'STANDARD', header: { type: 'NONE' }, body: auth ? '' : draft.body, examples: auth ? [] : draft.examples, parameterLabels: auth ? [] : draft.parameterLabels, footer: '', buttons: [], authentication: undefined, carousel: undefined, limitedTimeOffer: undefined })
  }
  const submit = async () => {
    setAttempted(true); setError(''); if (validation || unsupported) return
    setSaving(true)
    try { const result = template ? await api.updateTemplate(template.id, draft) : await api.createTemplate(draft); created(result); close() }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to save template') }
    finally { setSaving(false) }
  }
  const saveDraft = () => { try { sessionStorage.setItem(`relay_template_draft_${template?.id || 'new'}`, JSON.stringify(draft)); setDraftNotice('Draft saved in this browser tab.') } catch { setDraftNotice('This browser could not save the draft.') } }
  const restoreDraft = () => { try { const stored = sessionStorage.getItem(`relay_template_draft_${template?.id || 'new'}`); if (!stored) return setDraftNotice('No saved draft in this browser tab.'); const data = JSON.parse(stored); if (!data || !Array.isArray(data.buttons) || !Array.isArray(data.examples) || typeof data.body !== 'string') throw new Error(); setHeaderPreview(''); setTemplateName(friendlyName(data.name || '')); setDraft(data); setDraftNotice('Saved draft restored.') } catch { setDraftNotice('The saved draft could not be restored.') } }
  const headerTypes: HeaderType[] = kind === 'MPM' ? ['NONE', 'TEXT'] : kind === 'LIMITED_TIME_OFFER' ? ['NONE', 'IMAGE', 'VIDEO'] : ['NONE', 'TEXT', 'IMAGE', 'VIDEO', 'DOCUMENT', 'LOCATION']
  const headerKeys = variableKeys(draft.header?.text), headerFieldKey = fieldKey(headerFieldName)
  const insertHeaderField = () => {
    if (headerKeys.length) return
    const key = format === 'NAMED' ? headerFieldKey : '1'
    if (!key) return
    const text = draft.header?.text || ''
    patch({ header: { ...draft.header!, text: `${text}${text && !/\s$/.test(text) ? ' ' : ''}{{${key}}}` } })
    setHeaderFieldName('')
  }
  return <div className="overlay template-overlay"><div className="template-editor" role="dialog" aria-modal="true" aria-labelledby="template-editor-title" tabIndex={-1} {...dialog}>
    <div className="template-editor-head"><div><h2 id="template-editor-title">{template ? 'Edit template' : 'Create WhatsApp template'}</h2><p>Build your message and submit it to Meta for approval.</p></div><button type="button" aria-label="Close template editor" onClick={close} disabled={busy}><X size={20} /></button></div>
    {unsupported ? <div className="template-section"><p role="alert">{unsupported}</p><a href="https://business.facebook.com/latest/whatsapp_manager/message_templates" target="_blank" rel="noreferrer">Open WhatsApp Manager</a></div> : <div className="template-editor-layout"><form onSubmit={e => { e.preventDefault(); void submit() }} noValidate>
      {template?.rejectionReason && <p className="template-error">Meta review feedback: {template.rejectionReason}</p>}
      <fieldset disabled={busy}>
        <section className="template-section"><h3>1. Template details</h3><label>Template name<input value={templateName} maxLength={512} disabled={Boolean(template)} onChange={e => { setTemplateName(e.target.value); patch({ name: templateKey(e.target.value) }) }} placeholder="Order Ready" /></label><small>Use a clear name your team will recognize, such as “Appointment Reminder.” It cannot be changed after creation.</small><div className="template-grid"><label>Category<select value={draft.category} disabled={Boolean(template)} onChange={e => setCategory(e.target.value)}><option value="UTILITY">Utility</option><option value="MARKETING">Marketing</option><option value="AUTHENTICATION">Authentication</option></select></label><label>Language<select value={draft.language} disabled={Boolean(template)} onChange={e => patch({ language: e.target.value })}>{TEMPLATE_LANGUAGES.map(([code, name]) => <option key={code} value={code}>{name}</option>)}</select></label></div><small>{auth ? 'One-time passwords and verification codes.' : draft.category === 'UTILITY' ? 'Updates about an existing transaction, appointment or service.' : 'Promotions, offers, product recommendations and other marketing messages.'}</small>
        {!auth && availableKinds.length > 1 && <label>Message format<select value={kind} onChange={e => setKind(e.target.value as TemplateKind)}>{availableKinds.map(([candidate, name]) => <option key={candidate} value={candidate}>{name}</option>)}</select></label>}
        </section>
        {auth ? <section className="template-section"><h3>2. Authentication settings</h3><label>Code delivery<select value={draft.authentication?.otpType} onChange={e => patch({ authentication: { ...draft.authentication!, otpType: e.target.value as any, zeroTapTermsAccepted: false } })}><option value="COPY_CODE">Copy code</option><option value="ONE_TAP">Android one-tap autofill</option><option value="ZERO_TAP">Android zero-tap</option></select></label><label className="template-check"><input type="checkbox" checked={draft.authentication?.addSecurityRecommendation} onChange={e => patch({ authentication: { ...draft.authentication!, addSecurityRecommendation: e.target.checked } })} /> Include security recommendation</label><label>Code expiration notice (optional, 1–90 minutes)<input type="number" min={1} max={90} value={draft.authentication?.codeExpirationMinutes ?? ''} onChange={e => patch({ authentication: { ...draft.authentication!, codeExpirationMinutes: e.target.value === '' ? undefined : Number(e.target.value) } })} /></label><label>Copy button label<input maxLength={25} value={draft.authentication?.buttonText || ''} onChange={e => patch({ authentication: { ...draft.authentication!, buttonText: e.target.value } })} /></label>{draft.authentication?.otpType !== 'COPY_CODE' && <><label>Android package name<input value={draft.authentication?.packageName || ''} onChange={e => patch({ authentication: { ...draft.authentication!, packageName: e.target.value } })} placeholder="com.example.app" /></label><label>App signature hash<input maxLength={11} value={draft.authentication?.signatureHash || ''} onChange={e => patch({ authentication: { ...draft.authentication!, signatureHash: e.target.value } })} /></label><label>Autofill button label<input maxLength={25} value={draft.authentication?.autofillText || ''} onChange={e => patch({ authentication: { ...draft.authentication!, autofillText: e.target.value } })} /></label></>}{draft.authentication?.otpType === 'ZERO_TAP' && <label className="template-check"><input type="checkbox" checked={draft.authentication.zeroTapTermsAccepted || false} onChange={e => patch({ authentication: { ...draft.authentication!, zeroTapTermsAccepted: e.target.checked } })} /> I accept Meta’s zero-tap terms and have configured the Android app to receive codes.</label>}<small>WhatsApp supplies the message text. The expiration notice does not expire codes in your authentication backend.</small></section> : <>
        {!['CAROUSEL', 'PRODUCT_CAROUSEL', 'CATALOG', 'SPM'].includes(kind) && <section className="template-section"><h3>2. Header <small>Optional</small></h3><label>Header type<select value={draft.header?.type || 'NONE'} onChange={e => { setHeaderFieldName(''); patch({ header: { type: e.target.value as HeaderType, text: '', example: '' } }) }}>{headerTypes.map(t => <option key={t} value={t}>{t === 'NONE' ? 'No header' : title(t)}</option>)}</select></label>{draft.header?.type === 'TEXT' && <><label>Header text<input value={draft.header.text || ''} onChange={e => patch({ header: { ...draft.header!, text: e.target.value } })} placeholder="Your appointment with" /></label><small>Up to 60 characters and one personalization field. Plain text only.</small>{!headerKeys.length && (format === 'NAMED' ? <><div className="template-inline"><label>Personalization field<input value={headerFieldName} onChange={e => setHeaderFieldName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); insertHeaderField() } }} placeholder="Doctor Name" /></label><button type="button" onClick={insertHeaderField} disabled={!headerFieldKey}><Plus size={13} /> Add field</button></div><small>For example, “Doctor Name” is inserted as {'{{doctor_name}}'}.</small></> : <button type="button" onClick={insertHeaderField}><Plus size={13} /> Add personalization field</button>)}{headerKeys.length > 0 && <div className="template-subcard"><div className="template-inline"><b>{friendlyName(headerKeys[0])}</b><button type="button" aria-label="Remove header personalization field" onClick={() => patch({ header: { ...draft.header!, text: (draft.header?.text || '').replaceAll(`{{${headerKeys[0]}}}`, '').replace(/ {2,}/g, ' ').trim(), example: '' } })}><Trash2 size={14} /> Remove field</button></div><label>Example value for this field<input value={draft.header.example || ''} onChange={e => patch({ header: { ...draft.header!, example: e.target.value } })} placeholder="Dr Sharma" /></label></div>}</>}{draft.header && ['IMAGE', 'VIDEO', 'DOCUMENT'].includes(draft.header.type) && <MediaPicker key={draft.header.type} type={draft.header.type as 'IMAGE' | 'VIDEO' | 'DOCUMENT'} value={draft.header.example} onChange={example => setDraft(d => ({ ...d, header: { ...d.header!, example } }))} onBusy={setUploading} onPreview={setHeaderPreview} />}{draft.header?.type === 'LOCATION' && <p className="template-note"><b>Location details are added when this template is sent.</b><br />The sender will enter the location name, address and map coordinates, so the same approved template can be used for different places.</p>}</section>}
        {['CATALOG', 'MPM', 'SPM'].includes(kind) && <p className="template-note">Connect an ecommerce catalog to your WhatsApp account first. Products are selected when sending. {kind === 'SPM' && 'The product supplies the header image.'}</p>}
        <section className="template-section"><h3>3. Message content</h3>{kind === 'LIMITED_TIME_OFFER' && <><label>Offer title<input maxLength={16} value={draft.limitedTimeOffer?.text || ''} onChange={e => patch({ limitedTimeOffer: { ...draft.limitedTimeOffer!, text: e.target.value } })} /></label><label className="template-check"><input type="checkbox" checked={draft.limitedTimeOffer?.hasExpiration || false} onChange={e => patch({ limitedTimeOffer: { ...draft.limitedTimeOffer!, hasExpiration: e.target.checked } })} /> Show expiration countdown</label></>}<TextEditor label={['CAROUSEL', 'PRODUCT_CAROUSEL'].includes(kind) ? 'Message above the carousel' : 'Message body'} value={draft.body} examples={draft.examples} labels={draft.parameterLabels} format={format} max={kind === 'SPM' ? 160 : kind === 'LIMITED_TIME_OFFER' ? 600 : 1024} onChange={(body, examples, parameterLabels) => patch({ body, examples, parameterLabels })} />{!['CAROUSEL', 'PRODUCT_CAROUSEL', 'LIMITED_TIME_OFFER'].includes(kind) && <label>Footer <small>Optional · 60 characters · plain text, no variables</small><input maxLength={60} value={draft.footer || ''} onChange={e => patch({ footer: e.target.value })} placeholder="Thank you for choosing us" /></label>}</section>
        {['CAROUSEL', 'PRODUCT_CAROUSEL'].includes(kind) ? <section className="template-section"><h3>4. Carousel cards</h3><small>{kind === 'PRODUCT_CAROUSEL' ? 'Define two product cards with the same button type. Select 2–10 catalog products when sending.' : '2–10 cards. Use the same media type and button layout for every card. Card bodies are optional, but must be present on all cards if used.'}</small>{draft.carousel?.cards.map((card, i) => {
          const change = (data: Partial<typeof card>) => setDraft(d => ({ ...d, carousel: { cards: d.carousel!.cards.map((c, n) => i === n ? { ...c, ...data } : c) } }))
          return <article className="template-subcard" key={i}><div className="template-inline"><h4>Card {i + 1}</h4><button type="button" aria-label={`Remove card ${i + 1}`} disabled={draft.carousel!.cards.length <= 2} onClick={() => patch({ carousel: { cards: draft.carousel!.cards.filter((_, n) => i !== n) } })}><Trash2 size={16} /></button></div>{kind !== 'PRODUCT_CAROUSEL' && <><label>Media type<select value={card.headerType} onChange={e => change({ headerType: e.target.value as 'IMAGE' | 'VIDEO', headerExample: '' })}><option value="IMAGE">Image</option><option value="VIDEO">Video</option></select></label><MediaPicker key={card.headerType} type={card.headerType as 'IMAGE' | 'VIDEO'} value={card.headerExample} onChange={headerExample => change({ headerExample })} onBusy={setUploading} /><TextEditor label="Card body (optional)" value={card.body} examples={card.examples} format={format} max={160} onChange={(body, examples) => change({ body, examples })} /></>}<ButtonEditor buttons={card.buttons} onChange={buttons => change({ buttons })} allowed={kind === 'PRODUCT_CAROUSEL' ? ['SPM', 'URL'] : ['QUICK_REPLY', 'URL', 'PHONE_NUMBER']} max={kind === 'PRODUCT_CAROUSEL' ? 1 : 2} /></article>
        })}<button type="button" disabled={kind === 'PRODUCT_CAROUSEL' || (draft.carousel?.cards.length || 0) >= 10} onClick={() => { const first = draft.carousel!.cards[0]; patch({ carousel: { cards: [...draft.carousel!.cards, { headerType: first.headerType, headerExample: '', body: first.body, examples: first.examples.slice(), buttons: first.buttons.map(b => ({ ...b })) }] } }) }}><Plus size={14} /> Add card with matching layout</button></section> : !['CATALOG', 'MPM', 'SPM'].includes(kind) && <section className="template-section"><h3>4. Buttons <small>{kind === 'STANDARD' ? 'Optional' : 'Website button required'}</small></h3><ButtonEditor buttons={draft.buttons} onChange={buttons => patch({ buttons })} allowed={kind === 'LIMITED_TIME_OFFER' ? ['COPY_CODE', 'URL'] : draft.category === 'MARKETING' ? ['QUICK_REPLY', 'URL', 'PHONE_NUMBER', 'COPY_CODE', 'FLOW'] : ['QUICK_REPLY', 'URL', 'PHONE_NUMBER', 'FLOW']} max={kind === 'LIMITED_TIME_OFFER' ? 2 : 10} /></section>}
        </>}
        <div className="template-note">Meta reviews submitted templates and may change their category. GIF headers, payment templates and WhatsApp calling buttons require additional APIs or account setup; manage those in <a href="https://business.facebook.com/latest/whatsapp_manager/message_templates" target="_blank" rel="noreferrer">WhatsApp Manager</a>.</div>
      </fieldset>
      {(error || attempted && validation) && <p className="template-error" role="alert">{error || validation}</p>}
      {draftNotice && <p role="status">{draftNotice}</p>}
      <div className="template-editor-actions"><button type="button" disabled={busy} onClick={saveDraft}>Save draft</button><button type="button" disabled={busy} onClick={restoreDraft}>Restore draft</button><button className="new-template" type="submit" disabled={busy}>{uploading ? 'Uploading…' : saving ? 'Submitting…' : template ? 'Submit changes for review' : 'Submit to Meta'}</button></div>
    </form><Preview draft={draft} headerPreview={headerPreview} /></div>}
  </div></div>
}
