import { useEffect, useRef, useState } from 'react'
import { ArrowDown, ArrowUp, CalendarDays, Check, Copy, FileJson, Plus, RefreshCw, Send, Settings, Trash2, Workflow, X } from 'lucide-react'
import { api, type ApiConversation, type ApiUser } from '../api'
import { appointmentFlow, blankFlow, componentExample, connectFormAnswers, FLOW_CATEGORIES, FLOW_COMPONENTS, isEditableFlow, validateFlowJson, type FlowInput, type FlowObject, type NativeFlow } from '../../shared/whatsapp-flows'
import { flowsApi, type FlowSetup, type FlowSlot } from './api'
import { useDialog } from '../templates/TemplateModal'
import './flows.css'

const title = (s: string) => s.toLowerCase().replaceAll('_', ' ').replace(/^./, c => c.toUpperCase())
const statusLabel = (s: string) => s === 'LOCAL_DRAFT' ? 'Draft · saved here' : s === 'DRAFT' ? 'Draft · on Meta' : s === 'DEPRECATED' ? 'Retired' : title(s)
const fieldNames: Record<string, string> = { TextHeading: 'Heading', TextSubheading: 'Subheading', TextBody: 'Paragraph', TextCaption: 'Small text', TextInput: 'Short answer', TextArea: 'Long answer', Dropdown: 'Dropdown', RadioButtonsGroup: 'Single choice', CheckboxGroup: 'Multiple choice', DatePicker: 'Date', OptIn: 'Consent', Footer: 'Continue button', Image: 'Image', Form: 'Field group', CalendarPicker: 'Calendar', ChipsSelector: 'Choice chips', PhotoPicker: 'Upload photos', DocumentPicker: 'Upload documents', EmbeddedLink: 'Link', NavigationList: 'Navigation list', RichText: 'Formatted text', ImageCarousel: 'Image carousel', If: 'Conditional content', Switch: 'Conditional branches' }
const err = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong. Please try again.'

export function WhatsAppFlows({ user }: { user: ApiUser }) {
  const [flows, setFlows] = useState<NativeFlow[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
  const [editor, setEditor] = useState<NativeFlow | FlowInput | null>(null), [starter, setStarter] = useState(false), [settings, setSettings] = useState(false), [sending, setSending] = useState<NativeFlow | null>(null), [query, setQuery] = useState('')
  const admin = user.role === 'ADMIN', file = useRef<HTMLInputElement>(null)
  const load = () => flowsApi.list().then(setFlows)
  useEffect(() => { load().catch(e => setError(err(e))).finally(() => setLoading(false)) }, [])
  const update = (flow: NativeFlow) => setFlows(all => [flow, ...all.filter(item => item.id !== flow.id)])
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn() } catch (e) { setError(err(e)) } finally { setBusy(false) } }
  function start(kind: string) {
    let flowJson = kind === 'appointment' ? appointmentFlow() : blankFlow()
    if (kind === 'contact') flowJson.screens[0] = { ...flowJson.screens[0], title: 'Contact us', layout: { type: 'SingleColumnLayout', children: [{ type: 'Form', name: 'contact', children: [componentExample('TextInput', 'name'), { ...componentExample('TextInput', 'email'), label: 'Email address', 'input-type': 'email' }, { ...componentExample('TextArea', 'message'), label: 'How can we help?' }, { type: 'Footer', label: 'Send details', 'on-click-action': { name: 'complete', payload: { name: '${form.name}', email: '${form.email}', message: '${form.message}' } } }] }] } }
    if (kind === 'contact') flowJson.screens[0].layout.children[0].children[0].label = 'Your name'
    if (kind === 'survey') flowJson.screens[0].layout.children = [{ type: 'Form', name: 'feedback', children: [{ type: 'RadioButtonsGroup', name: 'rating', label: 'How was your experience?', required: true, 'data-source': [{ id: 'great', title: 'Great' }, { id: 'okay', title: 'Okay' }, { id: 'poor', title: 'Could be better' }] }, { type: 'TextArea', name: 'feedback', label: 'Anything else to share?' }, { type: 'Footer', label: 'Send feedback', 'on-click-action': { name: 'complete', payload: { rating: '${form.rating}', feedback: '${form.feedback}' } } }] }]
    setEditor({ name: kind === 'appointment' ? 'Book an appointment' : kind === 'contact' ? 'Contact us' : kind === 'survey' ? 'Customer feedback' : 'New Flow', categories: [kind === 'appointment' ? 'APPOINTMENT_BOOKING' : kind === 'contact' ? 'CONTACT_US' : kind === 'survey' ? 'SURVEY' : 'OTHER'], endpointMode: kind === 'appointment' ? 'APPOINTMENT' : 'NONE', endpointUri: '', flowJson }); setStarter(false)
  }
  return <div className="wa-flows">
    <div className="wf-toolbar"><div><h2>Forms that stay in WhatsApp</h2><p>Collect details, hear feedback, or let customers book an appointment.</p></div><div className="wf-actions">{admin && <><button disabled={busy} onClick={() => setSettings(true)}><Settings size={16} />Setup & availability</button><button disabled={busy} onClick={() => run(async () => { const result = await flowsApi.sync(); await load(); setNotice(`${result.count} Flows synced from Meta.`) })}><RefreshCw size={16} />Sync from Meta</button><button className="wf-primary" onClick={() => setStarter(true)}><Plus size={16} />Create Flow</button></>}</div></div>
    {error && <p role="alert" className="wf-error">{error}</p>}{notice && <p role="status" className="wf-success">{notice}</p>}
    <label className="wf-search">Search Flows<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name or status" /></label>
    {loading ? <p role="status">Loading your Flows…</p> : <div className="wf-grid">{flows.filter(flow => `${flow.name} ${flow.status}`.toLowerCase().includes(query.toLowerCase())).map(flow => <article className="wf-card" key={flow.id}><div className="wf-card-top"><span className="wf-icon">{flow.endpointMode === 'APPOINTMENT' ? <CalendarDays /> : <Workflow />}</span><span className={`wf-status wf-${flow.status.toLowerCase()}`}>{statusLabel(flow.status)}</span></div><h3>{flow.name}</h3><p>{flow.categories.map(title).join(' · ')}</p><small>{flow.flowJson.screens?.length || 0} screens{flow.endpointMode === 'APPOINTMENT' ? ' · Live appointment booking' : flow.endpointMode === 'EXTERNAL' ? ' · Connected to your backend' : ' · Form responses'}</small>{flow.validationErrors?.length > 0 && <p className="wf-error">{flow.validationErrors.length} things to fix before publishing</p>}<div className="wf-card-actions"><button onClick={() => setEditor(flow)}>{admin && isEditableFlow(flow.status) ? 'Edit Flow' : 'View Flow'}</button>{admin && <button title="Make a copy" aria-label={`Copy ${flow.name}`} disabled={busy} onClick={() => run(async () => { const copy = await flowsApi.action(flow, 'copy'); update(copy); setEditor(copy) })}><Copy size={16} /></button>}{['PUBLISHED', ...(admin ? ['DRAFT'] : [])].includes(flow.status) && <button onClick={() => setSending(flow)}><Send size={15} />{flow.status === 'DRAFT' ? 'Test' : 'Send'}</button>}</div></article>)}</div>}
    {!loading && !flows.length && <div className="wf-empty"><Workflow size={42} /><h3>Create your first customer experience</h3><p>Start with a ready-made form and make it yours.</p>{admin && <button className="wf-primary" onClick={() => setStarter(true)}>Choose a starter</button>}</div>}
    {starter && <Dialog title="What would you like customers to do?" close={() => setStarter(false)}><div className="wf-starters">{[['appointment', 'Book an appointment', 'Live times from your backend, a review step, and booking confirmation.'], ['contact', 'Share their details', 'Name, email, and a message. Ready to personalize.'], ['survey', 'Give feedback', 'A quick rating and an optional comment.'], ['blank', 'Build something new', 'Start with one screen and add your own fields.']].map(([kind, name, description]) => <button key={kind} onClick={() => start(kind)}><b>{name}</b><span>{description}</span></button>)}</div><input type="file" accept=".json,application/json" hidden ref={file} onChange={e => { const selected = e.target.files?.[0]; if (!selected) return; run(async () => { if (selected.size > 1_000_000) throw new Error('Choose a JSON file smaller than 1 MB'); const flowJson = JSON.parse(await selected.text()); const errors = validateFlowJson(flowJson); if (errors.length) throw new Error(errors.join('; ')); setEditor({ name: selected.name.replace(/\.json$/i, ''), categories: ['OTHER'], flowJson, endpointMode: flowJson.data_api_version ? 'EXTERNAL' : 'NONE', endpointUri: '' }); setStarter(false) }) }} /><button onClick={() => file.current?.click()}><FileJson size={16} />Import a Flow JSON file</button>{error && <p role="alert" className="wf-error">{error}</p>}</Dialog>}
    {editor && <FlowEditor key={'id' in editor ? editor.id : 'new'} initial={editor} admin={admin} close={() => setEditor(null)} saved={update} deleted={id => { setFlows(all => all.filter(flow => flow.id !== id)); setEditor(null) }} />}
    {settings && <SetupDialog close={() => setSettings(false)} />}
    {sending && <SendFlowDialog flow={sending} user={user} close={() => setSending(null)} />}
  </div>
}

function Dialog({ title, close, busy = false, wide = false, children }: { title: string; close: () => void; busy?: boolean; wide?: boolean; children: React.ReactNode }) {
  const dialog = useDialog(close, busy)
  return <div className="wf-overlay"><div className={`wf-dialog ${wide ? 'wf-wide' : ''}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={dialog.ref} onKeyDown={dialog.onKeyDown}><div className="wf-dialog-head"><h2>{title}</h2><button disabled={busy} onClick={close} aria-label="Close"><X size={20} /></button></div>{children}</div></div>
}
type LocatedField = { component: FlowObject; path: number[] }
function fields(children: FlowObject[], parent: number[] = []): LocatedField[] {
  return children.flatMap((component, i) => [{ component, path: [...parent, i] }, ...(Array.isArray(component.children) ? fields(component.children, [...parent, i]) : [])])
}
function getChildren(screen: FlowObject, path: number[]) { let children = screen.layout.children; for (const i of path.slice(0, -1)) children = children[i].children; return children as FlowObject[] }
function FlowEditor({ initial, admin, close, saved, deleted }: { initial: NativeFlow | FlowInput; admin: boolean; close: () => void; saved: (flow: NativeFlow) => void; deleted: (id: string) => void }) {
  const [value, setValue] = useState(initial), [baseline, setBaseline] = useState(JSON.stringify(initial)), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [screenIndex, setScreenIndex] = useState(0), [selected, setSelected] = useState<number[]>(initial.flowJson.screens?.[0]?.layout?.children?.[0]?.type === 'Form' ? [0, initial.endpointMode === 'APPOINTMENT' ? 1 : 0] : [0]), [advanced, setAdvanced] = useState(false), [raw, setRaw] = useState(''), [confirm, setConfirm] = useState(''), [preview, setPreview] = useState('')
  const current = 'id' in value ? value : null, editable = admin && (!current || isEditableFlow(current.status)), dirty = JSON.stringify(value) !== baseline, rawDirty = advanced && raw !== JSON.stringify(value.flowJson, null, 2)
  const screen = value.flowJson.screens?.[screenIndex], list = screen ? fields(screen.layout.children) : [], selectedField = list.find(field => field.path.join('.') === selected.join('.'))?.component
  const localErrors = validateFlowJson(value.flowJson), booking = value.endpointMode === 'APPOINTMENT'
  const published = current?.status === 'PUBLISHED'
  const stage = !current || current.status === 'LOCAL_DRAFT' ? 1 : current.status === 'DRAFT' && (current.syncedRevision !== current.revision || current.validationErrors.length > 0) ? 2 : current.status === 'DRAFT' ? 3 : 4
  const finish = (flow: NativeFlow) => { setValue(flow); setBaseline(JSON.stringify(flow)); saved(flow) }
  const leave = () => { if (!(dirty || rawDirty) || window.confirm('Discard your unsaved changes?')) close() }
  useEffect(() => { const handler = (e: BeforeUnloadEvent) => { if (dirty || rawDirty) { e.preventDefault(); e.returnValue = '' } }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler) }, [dirty, rawDirty])
  const patch = (change: Partial<FlowInput>) => { setValue(v => ({ ...v, ...change })); setPreview(''); setNotice('') }
  const editDoc = (fn: (doc: FlowObject) => void) => { if (!editable || busy) return; const doc = structuredClone(value.flowJson); fn(doc); if (!booking) connectFormAnswers(doc); patch({ flowJson: doc }) }
  const editField = (change: FlowObject) => editDoc(doc => { const children = getChildren(doc.screens[screenIndex], selected); children[selected.at(-1)!] = { ...children[selected.at(-1)!], ...change } })
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn() } catch (e) { setError(err(e)) } finally { setBusy(false) } }
  async function save() { const flow = current ? await flowsApi.save(current.id, value) : await flowsApi.create(value); finish(flow); return flow }
  function addField(type: string) {
    const key = `field_${Date.now().toString(36)}`
    editDoc(doc => {
      const children = doc.screens[screenIndex].layout.children, formIndex = children.findIndex((item: FlowObject) => item.type === 'Form')
      const target = formIndex >= 0 ? children[formIndex].children : children
      const footer = target.findIndex((item: FlowObject) => item.type === 'Footer'), index = footer >= 0 && type !== 'Footer' ? footer : target.length
      target.splice(index, 0, componentExample(type, key)); setSelected(formIndex >= 0 ? [formIndex, index] : [index])
      const submit = target.find((item: FlowObject) => item.type === 'Footer')
      if (formIndex >= 0 && submit?.['on-click-action']?.name === 'complete' && target[index].name) submit['on-click-action'].payload = { ...submit['on-click-action'].payload, [key]: '${form.' + key + '}' }
    })
  }
  function setNext(target: string) {
    editDoc(doc => {
      const currentScreen = doc.screens[screenIndex], children = getChildren(currentScreen, selected), field = children[selected.at(-1)!]
      const payload: FlowObject = {}
      for (const key of Object.keys(currentScreen.data || {})) payload[key] = '${data.' + key + '}'
      for (const item of fields(currentScreen.layout.children)) if (item.component.name && item.component.type !== 'Form') payload[item.component.name] = '${form.' + item.component.name + '}'
      field['on-click-action'] = target ? { name: 'navigate', next: { type: 'screen', name: target }, payload } : { name: 'complete', payload }
      currentScreen.terminal = !target
      if (!target) currentScreen.success = true; else delete currentScreen.success
      if (target) {
        const next = doc.screens.find((item: FlowObject) => item.id === target)
        next.data ||= {}
        for (const [key, ref] of Object.entries(payload)) {
          const source = fields(currentScreen.layout.children).find(item => item.component.name === key)?.component
          next.data[key] ||= currentScreen.data?.[key] || (source?.type === 'OptIn' ? { type: 'boolean', __example__: false } : ['CheckboxGroup', 'ChipsSelector'].includes(source?.type) ? { type: 'array', items: { type: 'string' }, __example__: ['option_1'] } : { type: 'string', __example__: 'Example' })
          void ref
        }
      }
      if (doc.routing_model) doc.routing_model[currentScreen.id] = target ? [target] : []
    })
  }
  return <Dialog title={current ? value.name : 'Create a WhatsApp Flow'} close={leave} busy={busy} wide>
    <div className="wf-editor-bar"><span className="wf-status">{current ? statusLabel(current.status) : 'New draft'}</span><small>{dirty ? 'Unsaved changes' : current ? 'All changes saved' : 'Choose your settings below'}</small><div className="wf-actions"><button onClick={() => { const blob = new Blob([JSON.stringify(value.flowJson, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'flow.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }}>Export</button><button onClick={() => { if (rawDirty && !window.confirm('Discard unapplied JSON changes?')) return; setAdvanced(!advanced); setRaw(JSON.stringify(value.flowJson, null, 2)) }}>{advanced ? 'Back to builder' : 'Advanced'}</button></div></div>
    <ol className="wf-progress" aria-label="Flow publishing progress">{['Create & save', 'Check with Meta', 'Preview & publish', 'Ready to send'].map((label, index) => <li key={label} className={stage > index + 1 ? 'done' : stage === index + 1 ? 'current' : ''}><span>{stage > index + 1 ? <Check size={13} /> : index + 1}</span>{label}</li>)}</ol>
    {published && <div className="wf-publish-complete" role="status" aria-live="polite"><span><Check size={18} /></span><div><b>Flow published and ready to send</b><small>Meta accepted this Flow. Its screens are now locked; make a copy if you need to change them.</small></div></div>}
    {!editable && <p className="wf-info">{admin ? 'Published screens are locked. Make a copy to create a new version.' : 'You can preview this Flow. An administrator can make changes.'}</p>}
    <fieldset disabled={!editable || busy} className="wf-basics"><label>Flow name<input value={value.name} maxLength={200} onChange={e => patch({ name: e.target.value })} /></label><label>Purpose<select value={value.categories[0]} onChange={e => patch({ categories: [e.target.value] })}>{FLOW_CATEGORIES.map(category => <option key={category} value={category}>{title(category)}</option>)}</select></label></fieldset>
    {booking && <p className="wf-info"><CalendarDays size={16} />This starter uses your appointment backend. Edit the wording below; appointment fields and booking steps stay connected automatically. Manage real appointment times in Setup & availability.</p>}
    {advanced ? <div className="wf-advanced"><fieldset disabled={!editable || busy}><label>Backend connection<select value={value.endpointMode} onChange={e => patch({ endpointMode: e.target.value as FlowInput['endpointMode'] })}><option value="NONE">No backend — collect form responses</option><option value="APPOINTMENT">Built-in appointment booking</option><option value="EXTERNAL">My own backend endpoint</option></select></label>{value.endpointMode === 'EXTERNAL' && <label>Public HTTPS endpoint<input value={value.endpointUri} onChange={e => patch({ endpointUri: e.target.value })} placeholder="https://your-service.example/flows" /></label>}<label>Categories{FLOW_CATEGORIES.map(category => <span className="wf-check" key={category}><input type="checkbox" checked={value.categories.includes(category)} onChange={e => patch({ categories: e.target.checked ? [...value.categories, category] : value.categories.filter(c => c !== category) })} />{title(category)}</span>)}</label><label>Complete Flow JSON<textarea className="wf-code" rows={22} value={raw} onChange={e => setRaw(e.target.value)} spellCheck={false} /></label><button type="button" onClick={() => { try { const flowJson = JSON.parse(raw); const errors = validateFlowJson(flowJson); if (errors.length) throw new Error(errors.join('; ')); patch({ flowJson }); setScreenIndex(0); setNotice('JSON applied to the builder. Save your changes next.'); setError('') } catch (e) { setError(err(e)) } }}>Apply JSON changes</button></fieldset><p>All Meta properties are preserved. Use this for screen data, conditions, media, dynamic options and version-specific components. Check with Meta for full validation.</p></div> : <div className="wf-builder">
      <aside className="wf-screens"><h3>Screens</h3>{value.flowJson.screens?.map((item: FlowObject, i: number) => <button key={i} className={screenIndex === i ? 'selected' : ''} onClick={() => { setScreenIndex(i); setSelected([0]) }}><b>{i + 1}</b>{item.title || item.id}</button>)}{editable && !booking && <button onClick={() => editDoc(doc => { doc.screens.push({ id: `SCREEN_${Date.now().toString(36).toUpperCase()}`, title: 'New screen', terminal: true, success: true, data: {}, layout: { type: 'SingleColumnLayout', children: [{ type: 'Form', name: 'form', children: [{ type: 'Footer', label: 'Done', 'on-click-action': { name: 'complete', payload: {} } }] }] } }); setScreenIndex(doc.screens.length - 1); setSelected([0, 0]) })}><Plus size={15} />Add screen</button>}<small>Use a continue button to choose what opens next.</small></aside>
      <section className="wf-fields"><fieldset disabled={!editable || busy}><label>Screen title<input value={screen?.title || ''} onChange={e => editDoc(doc => { doc.screens[screenIndex].title = e.target.value })} /></label></fieldset>{list.filter(field => field.component.type !== 'Form').map(({ component, path }) => <button className={`wf-field ${path.join('.') === selected.join('.') ? 'selected' : ''}`} key={path.join('.')} style={{ marginLeft: (path.length - 1) * 12 }} onClick={() => setSelected(path)}><small>{fieldNames[component.type] || component.type}</small><span>{typeof component.label === 'string' ? component.label : typeof component.text === 'string' ? component.text.startsWith('${data.') ? 'Live content from your backend' : component.text : component.name || component.type}</span></button>)}{editable && !booking && <label>Add a field<select value="" onChange={e => { if (e.target.value) addField(e.target.value) }}><option value="">Choose a field…</option>{FLOW_COMPONENTS.map(type => <option key={type} value={type}>{fieldNames[type] || type}</option>)}</select></label>}{screen && editable && !booking && value.flowJson.screens.length > 1 && <button className="wf-danger" onClick={() => { if (!window.confirm('Remove this screen? Update any buttons that open it.')) return; editDoc(doc => { doc.screens.splice(screenIndex, 1); if (doc.routing_model) { delete doc.routing_model[screen.id]; for (const key of Object.keys(doc.routing_model)) doc.routing_model[key] = doc.routing_model[key].filter((id: string) => id !== screen.id) } }); setScreenIndex(0); setSelected([0]) }}><Trash2 size={14} />Remove screen</button>}</section>
      <section className="wf-properties"><h3>{selectedField ? fieldNames[selectedField.type] || selectedField.type : 'Choose a field'}</h3>{selectedField && <fieldset disabled={!editable || busy}>
        {(['text', 'label', 'helper-text'] as const).map(key => (key in selectedField || key === 'helper-text' && ['TextInput', 'TextArea'].includes(selectedField.type)) && <label key={key}>{key === 'text' ? 'Text' : key === 'label' ? 'Label' : 'Help text'}<textarea rows={key === 'text' ? 4 : 2} value={typeof selectedField[key] === 'string' ? selectedField[key] : ''} disabled={booking && String(selectedField[key]).startsWith('${data.')} onChange={e => editField({ [key]: e.target.value })} /></label>)}
        {selectedField.type === 'Image' && <><label>Image file<input type="file" accept="image/jpeg,image/png" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 600000) { setError('Choose an image smaller than 600 KB for this form.'); return } setBusy(true); try { const encoded = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('Unable to read this image')); reader.readAsDataURL(file) }); editField({ src: encoded.split(',')[1] }); setError('') } catch (error) { setError(err(error)) } finally { setBusy(false) } }} /></label><label>Image description<input value={selectedField['alt-text'] || ''} onChange={e => editField({ 'alt-text': e.target.value })} /></label><small>The image is embedded in your Flow. Check with Meta to validate its format and size.</small></>}
        {selectedField.type === 'EmbeddedLink' && <label>Website address<input type="url" value={selectedField['on-click-action']?.url || ''} onChange={e => editField({ 'on-click-action': { ...selectedField['on-click-action'], name: 'open_url', url: e.target.value } })} /></label>}
        {['PhotoPicker', 'DocumentPicker'].includes(selectedField.type) && <><label>Maximum files<input type="number" min={1} max={30} value={selectedField[selectedField.type === 'PhotoPicker' ? 'max-uploaded-photos' : 'max-uploaded-documents'] || 1} onChange={e => editField({ [selectedField.type === 'PhotoPicker' ? 'max-uploaded-photos' : 'max-uploaded-documents']: Number(e.target.value) })} /></label>{selectedField.type === 'PhotoPicker' && <label>Photo source<select value={selectedField['photo-source'] || 'camera_gallery'} onChange={e => editField({ 'photo-source': e.target.value })}><option value="camera_gallery">Camera or gallery</option><option value="camera">Camera only</option><option value="gallery">Gallery only</option></select></label>}<small>File limits and availability depend on the Flow version. Your backend handles submitted file metadata.</small></>}
        {'required' in selectedField && <label className="wf-check"><input type="checkbox" disabled={booking} checked={!!selectedField.required} onChange={e => editField({ required: e.target.checked })} />Answer required</label>}
        {selectedField.type === 'TextInput' && !booking && <label>Answer type<select value={selectedField['input-type'] || 'text'} onChange={e => editField({ 'input-type': e.target.value })}>{['text', 'email', 'number', 'phone', 'password', 'passcode'].map(type => <option key={type}>{type}</option>)}</select></label>}
        {Array.isArray(selectedField['data-source']) && <ChoiceEditor choices={selectedField['data-source']} change={choices => editField({ 'data-source': choices })} />}
        {selectedField.type === 'Footer' && !booking && <label>After this screen<select value={selectedField['on-click-action']?.name === 'navigate' ? selectedField['on-click-action'].next?.name || '' : selectedField['on-click-action']?.name === 'data_exchange' ? '__backend' : ''} onChange={e => { if (e.target.value === '__backend') editField({ 'on-click-action': { name: 'data_exchange', payload: {} } }); else setNext(e.target.value) }}><option value="">Finish and send answers</option>{value.flowJson.screens.filter((item: FlowObject) => item.id !== screen.id).map((item: FlowObject) => <option value={item.id} key={item.id}>Open {item.title || item.id}</option>)}{value.endpointMode !== 'NONE' && <option value="__backend">Continue through backend</option>}</select></label>}
        {!booking && <div className="wf-actions">{[-1, 1].map(direction => <button key={direction} aria-label={direction < 0 ? 'Move field up' : 'Move field down'} onClick={() => editDoc(doc => { const children = getChildren(doc.screens[screenIndex], selected), index = selected.at(-1)!, next = index + direction; if (next < 0 || next >= children.length) return; [children[index], children[next]] = [children[next], children[index]]; setSelected([...selected.slice(0, -1), next]) })}>{direction < 0 ? <ArrowUp size={15} /> : <ArrowDown size={15} />}</button>)}<button className="wf-danger" onClick={() => editDoc(doc => { getChildren(doc.screens[screenIndex], selected).splice(selected.at(-1)!, 1); setSelected([0]) })}><Trash2 size={15} />Remove</button></div>}
        {!booking && <details><summary>Advanced field settings</summary>{selectedField.name && <label>Answer key<input value={selectedField.name} onChange={e => editField({ name: e.target.value })} /></label>}<JsonProperties key={`${screenIndex}.${selected.join('.')}`} value={selectedField} apply={change => editDoc(doc => { getChildren(doc.screens[screenIndex], selected)[selected.at(-1)!] = change })} /></details>}
      </fieldset>}</section>
      <aside className="wf-preview"><small>Layout preview · example data</small><div className="wf-phone"><div className="wf-phone-head">{screen?.title || 'Your Flow'}</div>{screen && <PreviewFields items={screen.layout.children} data={Object.fromEntries(Object.entries(screen.data || {}).map(([key, value]) => [key, (value as any).__example__]))} />}</div><small>Use Meta preview to test navigation and supported components.</small></aside>
    </div>}
    {localErrors.length > 0 && <div className="wf-error">{localErrors.map(message => <p key={message}>{message}</p>)}</div>}{current?.validationErrors?.length ? <div className="wf-error"><b>Meta found these issues</b>{current.validationErrors.map((issue, i) => <p key={i}>{issue.message || issue.error}{issue.line_start ? ` (line ${issue.line_start})` : ''}</p>)}</div> : null}
    {error && <p className="wf-error" role="alert">{error}</p>}{notice && <p className="wf-success" role="status">{notice}</p>}{preview && <p><a href={preview} target="_blank" rel="noopener noreferrer">Open the interactive Meta preview ↗</a></p>}
    {current?.remoteDetails?.health_status && <details><summary>Delivery health from Meta</summary><pre>{JSON.stringify(current.remoteDetails.health_status, null, 2)}</pre></details>}
    {confirm && <div className="wf-confirm" role="alert"><p>{confirm === 'publish' ? `Publish “${value.name}”? Customers can use it after publishing. To change its screens later, you’ll need a new copy.` : confirm === 'deprecate' ? `Retire “${value.name}”? It will no longer be available for customers.` : `Permanently delete draft “${value.name}”?`}</p><button disabled={busy} onClick={() => setConfirm('')}>Cancel</button><button className="wf-primary" disabled={busy} onClick={() => run(async () => { if (!current) return; if (confirm === 'delete') { await flowsApi.delete(current); deleted(current.id) } else { finish(await flowsApi.action(current, confirm, { confirm: true })); setNotice(confirm === 'publish' ? 'Your Flow is published.' : 'Your Flow is retired.') } setConfirm('') })}>{busy ? confirm === 'publish' ? 'Publishing…' : 'Working…' : confirm === 'deprecate' ? 'Confirm retirement' : confirm === 'publish' ? 'Publish Flow' : 'Confirm delete'}</button></div>}
    <div className="wf-editor-footer"><div className="wf-actions">{current && admin && <><button disabled={busy || dirty || rawDirty} onClick={() => run(async () => { finish(await flowsApi.action(current, 'refresh')); setNotice('Status refreshed from Meta.') })}><RefreshCw size={15} />Refresh status</button>{isEditableFlow(current.status) ? <button disabled={busy || dirty} className="wf-danger" onClick={() => setConfirm('delete')}>Delete draft</button> : current.status !== 'DEPRECATED' && <button disabled={busy} className="wf-danger" onClick={() => setConfirm('deprecate')}>Retire Flow</button>}</>}{current?.metaFlowId && <button disabled={busy || dirty} onClick={() => run(async () => setPreview((await flowsApi.preview(current.id)).preview_url))}>Meta preview</button>}</div><div className="wf-actions">{editable && <><button disabled={busy || !!localErrors.length || advanced && raw !== JSON.stringify(value.flowJson, null, 2)} onClick={() => run(async () => { await save(); setNotice('Draft saved.') })}>Save draft</button><button className="wf-primary" disabled={busy || !!localErrors.length || advanced && raw !== JSON.stringify(value.flowJson, null, 2)} onClick={() => run(async () => { const latest = dirty || !current ? await save() : current; const checked = await flowsApi.action(latest, 'upload'); finish(checked); setNotice(checked.validationErrors.length ? 'Fix the issues above, then check again.' : 'Meta validation passed. Preview your Flow before publishing.') })}>{busy ? 'Working…' : 'Check with Meta'}</button>{current?.status === 'DRAFT' && current.syncedRevision === current.revision && !dirty && !current.validationErrors.length && <button className="wf-primary" disabled={busy} onClick={() => setConfirm('publish')}>Publish Flow</button>}</>}</div></div>
  </Dialog>
}

function ChoiceEditor({ choices, change }: { choices: FlowObject[]; change: (choices: FlowObject[]) => void }) {
  const nextId = () => {
    const used = new Set(choices.map(choice => String(choice.id)))
    let number = choices.length + 1
    while (used.has(`option_${number}`)) number++
    return `option_${number}`
  }
  return <div className="wf-choice-editor">
    <div className="wf-choice-heading"><span>Choices</span><small>{choices.length} {choices.length === 1 ? 'choice' : 'choices'}</small></div>
    <div className="wf-choice-list">{choices.map((choice, index) => <div className="wf-choice-row" key={`${choice.id}-${index}`}>
      <span className="wf-choice-number">{index + 1}</span>
      <input aria-label={`Choice ${index + 1}`} value={typeof choice.title === 'string' ? choice.title : ''} placeholder="Choice label" onChange={e => change(choices.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} />
      <button type="button" className="wf-danger" aria-label={`Remove choice ${index + 1}`} disabled={choices.length === 1} onClick={() => change(choices.filter((_, i) => i !== index))}><Trash2 size={15} /></button>
    </div>)}</div>
    <button type="button" className="wf-add-choice" onClick={() => change([...choices, { id: nextId(), title: '' }])}><Plus size={15} />Add choice</button>
    <small>Customers see these labels. Existing internal choice IDs stay unchanged when you edit a label.</small>
  </div>
}

function JsonProperties({ value, apply }: { value: FlowObject; apply: (value: FlowObject) => void }) {
  const [raw, setRaw] = useState(JSON.stringify(value, null, 2)), [error, setError] = useState('')
  useEffect(() => setRaw(JSON.stringify(value, null, 2)), [value])
  return <><textarea aria-label="Component JSON" className="wf-code" rows={10} value={raw} onChange={e => setRaw(e.target.value)} /><button onClick={() => { try { const parsed = JSON.parse(raw); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed) || typeof parsed.type !== 'string') throw new Error('A component needs a type'); apply(parsed); setError('') } catch (e) { setError(err(e)) } }}>Apply field settings</button>{error && <p className="wf-error">{error}</p>}</>
}
function PreviewFields({ items, data }: { items: FlowObject[]; data: FlowObject }) {
  const resolve = (value: any): any => typeof value === 'string' && value.startsWith('${data.') ? data[value.slice(7, -1)] ?? 'Example' : value
  return <div className="wf-preview-fields">{items.map((item, i) => {
    if (item.type === 'Form') return <PreviewFields key={i} items={item.children || []} data={data} />
    const text = String(resolve(item.text ?? item.label ?? item.type))
    if (item.type === 'Image' && typeof item.src === 'string' && /^[A-Za-z0-9+/=]+$/.test(item.src)) return <img key={i} src={'data:image/png;base64,' + item.src} alt={item['alt-text'] || 'Flow image'} style={{ maxWidth: '100%', maxHeight: 180, objectFit: 'contain' }} />
    if (item.type === 'Footer') return <div className="wf-preview-button" key={i}>{text}</div>
    if (['TextHeading', 'TextSubheading'].includes(item.type)) return <h3 key={i}>{text}</h3>
    if (['TextBody', 'TextCaption', 'RichText'].includes(item.type)) return <p key={i}>{text}</p>
    if (['Dropdown', 'RadioButtonsGroup', 'CheckboxGroup', 'ChipsSelector'].includes(item.type)) { const options = resolve(item['data-source']); return <div className="wf-preview-input" key={i}><b>{text}{item.required ? ' *' : ''}</b>{Array.isArray(options) ? options.slice(0, 4).map((option: FlowObject, j: number) => <small key={j}>{item.type === 'Dropdown' ? '⌄ ' : '○ '}{option.title}</small>) : <small>Options from your backend</small>}</div> }
    if (['TextInput', 'TextArea', 'DatePicker', 'CalendarPicker', 'OptIn'].includes(item.type)) return <div className="wf-preview-input" key={i}>{item.type === 'OptIn' ? '☐ ' : ''}{text}{item.required ? ' *' : ''}</div>
    return <div className="wf-preview-input" key={i}>{fieldNames[item.type] || item.type}<small>See Meta preview for this component</small></div>
  })}</div>
}

function SetupDialog({ close }: { close: () => void }) {
  const [setup, setSetup] = useState<FlowSetup | null>(null), [slots, setSlots] = useState<FlowSlot[]>([]), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [date, setDate] = useState(''), [count, setCount] = useState(1), [minutes, setMinutes] = useState(30)
  useEffect(() => { Promise.all([flowsApi.setup(), flowsApi.slots()]).then(([config, available]) => { setSetup(config); setSlots(available) }).catch(e => setError(err(e))) }, [])
  const run = async (fn: () => Promise<void>) => { setError(''); setNotice(''); setBusy(true); try { await fn() } catch (e) { setError(err(e)) } finally { setBusy(false) } }
  return <Dialog title="Setup & appointment availability" close={close} busy={busy}>
    <p>Forms work without a booking backend. Live appointments also need a secure connection to Meta.</p>{setup && <div className="wf-setup"><p>{setup.metaReady ? '✓' : '○'} WhatsApp account configured</p><p>{setup.endpointReady ? '✓' : '○'} Secure booking endpoint configured</p><details><summary>Connection details for your developer</summary><p>{setup.endpointUrl || 'Set WHATSAPP_FLOW_ENDPOINT_URL to your public HTTPS /api/whatsapp-flows/data endpoint.'}</p>{setup.keyError && <p>{setup.keyError}</p>}<p>Generate a key with <code>npm run flows:keygen</code>, configure the private key and app secret, then restart the backend.</p><button disabled={busy || !setup.publicKey || !setup.metaReady} onClick={() => { if (window.confirm('Register this public key for your WhatsApp number? This replaces the existing key and must match every live Flow endpoint using this number.')) void run(async () => { await flowsApi.registerKey(); setNotice('Public key registered with Meta.') }) }}>Register public key with Meta</button><button disabled={busy || !setup.metaReady} onClick={() => run(async () => { const response = await flowsApi.keyStatus(); const value = response.data?.[0] ?? response; setNotice(`Key status: ${value.business_public_key_signature_status || 'Not registered'}`) })}>Check registration</button></details></div>}
    <h3>Appointment times</h3><p>Only unbooked future times appear in the booking form. Add the actual availability for your business.</p><fieldset disabled={busy} className="wf-slot-form"><label>First appointment<input type="datetime-local" value={date} onChange={e => setDate(e.target.value)} /></label><div className="wf-two"><label>Number of times<input type="number" min={1} max={100} value={count} onChange={e => setCount(Number(e.target.value))} /></label><label>Minutes apart<input type="number" min={5} max={1440} value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></label></div><small>You’re entering times in {Intl.DateTimeFormat().resolvedOptions().timeZone}. Customers see {setup?.timezone || 'the business timezone'}.</small><button className="wf-primary" disabled={!date || !Number.isInteger(count) || count < 1 || count > 100 || !Number.isInteger(minutes) || minutes < 5 || minutes > 1440} onClick={() => run(async () => { await flowsApi.addSlots(Array.from({ length: count }, (_, i) => new Date(new Date(date).getTime() + i * minutes * 60000).toISOString())); setSlots(await flowsApi.slots()); setNotice('Appointment times added.') })}>Add available times</button></fieldset><div className="wf-slots">{slots.map(slot => <div key={slot.id}><span>{new Date(slot.startsAt).toLocaleString(undefined, { timeZone: setup?.timezone })}<small>{slot.appointment ? `Booked · ${slot.appointment.reference}` : 'Available'}</small></span>{!slot.appointment && <button aria-label="Remove available time" disabled={busy} onClick={() => run(async () => { await flowsApi.removeSlot(slot.id); setSlots(all => all.filter(item => item.id !== slot.id)) })}><Trash2 size={15} /></button>}</div>)}{!slots.length && <p>No upcoming appointment times yet.</p>}</div>
    {error && <p role="alert" className="wf-error">{error}</p>}{notice && <p role="status" className="wf-success">{notice}</p>}
  </Dialog>
}
function SendFlowDialog({ flow, user, close }: { flow: NativeFlow; user: ApiUser; close: () => void }) {
  const [conversations, setConversations] = useState<ApiConversation[]>([]), [conversationId, setConversationId] = useState(''), [body, setBody] = useState(flow.endpointMode === 'APPOINTMENT' ? 'Choose a convenient time for your appointment.' : 'Please fill in this form.'), [cta, setCta] = useState(flow.endpointMode === 'APPOINTMENT' ? 'Book appointment' : 'Open form'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [sent, setSent] = useState(false), [data, setData] = useState('{}'), [screen, setScreen] = useState(flow.flowJson.screens?.[0]?.id || ''), [externalToken, setExternalToken] = useState('')
  useEffect(() => { api.conversations().then(setConversations).catch(e => setError(err(e))) }, [])
  const choices = conversations.map(conversation => {
    const ownsClaim = conversation.claimedBy?.id === user.id || conversation.assignee?.id === user.id
    const receivedAt = conversation.lastCustomerMessageAt ? Date.parse(conversation.lastCustomerMessageAt) : NaN
    const reason = !conversation.claimedBy ? 'not claimed' : !ownsClaim ? `claimed by ${conversation.claimedBy.name}` : !Number.isFinite(receivedAt) ? 'no customer message received' : Date.now() - receivedAt >= 86400000 ? '24-hour window closed' : ''
    return { conversation, reason }
  })
  const eligibleCount = choices.filter(choice => !choice.reason).length
  return <Dialog title={flow.status === 'DRAFT' ? 'Send a draft test' : 'Send this Flow'} close={close} busy={busy}>{sent ? <p className="wf-success"><Check size={18} />Flow sent. Replies will appear in your inbox.</p> : <><p>Choose a conversation you own where the customer messaged in the last 24 hours. Ineligible conversations remain visible with the reason they cannot receive a direct Flow.</p><fieldset disabled={busy}><label>Customer<select value={conversationId} onChange={e => setConversationId(e.target.value)}><option value="">Choose a conversation</option>{choices.map(({ conversation, reason }) => <option key={conversation.id} value={conversation.id} disabled={!!reason}>{conversation.contact.profileName || conversation.contact.phone}{reason ? ` — ${reason}` : ''}</option>)}</select></label>{conversations.length > 0 && eligibleCount === 0 && <p className="wf-info">No conversations are currently eligible. Ask the customer to message again to reopen the 24-hour window, or use an approved template containing a Flow button.</p>}<label>Message<textarea value={body} maxLength={1024} onChange={e => setBody(e.target.value)} /><small>{body.length}/1,024 characters</small></label><label>Button label<input value={cta} maxLength={20} onChange={e => setCta(e.target.value)} /><small>{cta.length}/20 characters</small></label>{flow.endpointMode !== 'APPOINTMENT' && <details><summary>Advanced launch settings</summary><label>Opening screen<select value={screen} onChange={e => setScreen(e.target.value)}>{flow.flowJson.screens?.map((s: FlowObject) => <option key={s.id} value={s.id}>{s.title || s.id}</option>)}</select></label><label>Opening data (JSON)<textarea value={data} onChange={e => setData(e.target.value)} /></label>{flow.endpointMode === 'EXTERNAL' && <label>Session token from your backend<input value={externalToken} onChange={e => setExternalToken(e.target.value)} /></label>}</details>}<button className="wf-primary" disabled={!conversationId || !body.trim() || !cta.trim() || flow.endpointMode === 'EXTERNAL' && !externalToken.trim()} onClick={async () => { setBusy(true); setError(''); try { await flowsApi.send(flow.id, { conversationId, body, cta, draft: flow.status === 'DRAFT', data: JSON.parse(data), screen, externalToken }); setSent(true) } catch (e) { setError(err(e)) } finally { setBusy(false) } }}>{busy ? 'Sending…' : flow.status === 'DRAFT' ? 'Send test Flow' : 'Send Flow'}</button></fieldset></>}{error && <p role="alert" className="wf-error">{error}</p>}</Dialog>
}
