import { useState } from 'react'
import { ChevronDown, Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react'
import { api, type ApiAudience, type ApiContact } from '../api'

function ContactPicker({ contacts, selected, change }: { contacts: ApiContact[]; selected: string[]; change: (ids: string[]) => void }) {
  const [query, setQuery] = useState(''), [open, setOpen] = useState(true)
  const visible = contacts.filter(contact => `${contact.profileName || ''} ${contact.phone}`.toLowerCase().includes(query.toLowerCase()))
  const toggle = (id: string) => change(selected.includes(id) ? selected.filter(item => item !== id) : [...selected, id])
  const chosen = contacts.filter(contact => selected.includes(contact.id))
  return <div className="relative mt-3"><button type="button" className="flex w-full items-center justify-between rounded-lg border border-slate-300 bg-white px-3 py-3 text-left text-xs" onClick={() => setOpen(value => !value)}><span>{selected.length ? `${selected.length} contact${selected.length === 1 ? '' : 's'} selected` : 'Choose saved contacts'}</span><ChevronDown className={`size-4 transition ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="mt-2 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-lg"><div className="flex items-center border-b border-slate-200 px-3"><Search className="size-4 shrink-0 text-slate-400" /><input className="!m-0 !border-0 !px-2 !outline-none" placeholder="Search saved contacts" value={query} onChange={e => setQuery(e.target.value)} /></div><label className="!m-0 flex cursor-pointer items-center gap-3 border-b border-slate-200 bg-slate-50 px-3 py-3 text-xs"><input className="!m-0 !size-4 !w-4 shrink-0" type="checkbox" checked={contacts.length > 0 && selected.length === contacts.length} onChange={e => change(e.target.checked ? contacts.map(contact => contact.id) : [])} /><b>Select all ({contacts.length})</b></label><div className="max-h-56 overflow-auto">{visible.map(contact => <label key={contact.id} className="!m-0 flex cursor-pointer items-center gap-3 border-b border-slate-100 px-3 py-3 text-xs last:border-0"><input className="!m-0 !size-4 !w-4 shrink-0" type="checkbox" checked={selected.includes(contact.id)} onChange={() => toggle(contact.id)} /><span className="min-w-0"><b className="block truncate">{contact.profileName || 'Unnamed contact'}</b><small className="text-slate-400">+{contact.phone}</small></span></label>)}{!visible.length && <p className="m-0 p-5 text-center text-xs text-slate-400">No saved contacts found</p>}</div></div>}{chosen.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{chosen.map(contact => <span key={contact.id} className="inline-flex items-center gap-1 rounded-full bg-relay-50 px-3 py-1.5 text-[11px] text-relay-700">{contact.profileName || contact.phone}<button type="button" className="!border-0 !bg-transparent !p-0" aria-label={`Remove ${contact.profileName || contact.phone}`} onClick={() => toggle(contact.id)}><X className="size-3" /></button></span>)}</div>}</div>
}

export function Audiences({ audiences, contacts, refresh }: { audiences: ApiAudience[]; contacts: ApiContact[]; refresh: () => Promise<void> }) {
  const [editing, setEditing] = useState<ApiAudience | true | null>(null), [error, setError] = useState('')
  return <div className="templates"><div className="template-tools"><div><h2 className="m-0 font-display text-lg font-bold">Audiences</h2><p className="mt-1 text-xs text-slate-500">Save groups of contacts so you can message them together.</p></div><button className="new-template" onClick={() => setEditing(true)}><Plus /> Create audience</button></div>{error && <p className="template-error">{error}</p>}<div className="grid gap-4 lg:grid-cols-2">{audiences.map(audience => <article key={audience.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-relay-50 text-relay-600"><Users className="size-5" /></span><div className="flex-1"><h3 className="m-0 text-sm font-bold">{audience.name}</h3><p className="mt-1 text-xs text-slate-400">{audience.members.length} contact{audience.members.length === 1 ? '' : 's'}</p></div><button onClick={() => setEditing(audience)} aria-label="Edit audience"><Pencil className="size-4" /></button><button onClick={async () => { if (!confirm(`Delete “${audience.name}”?`)) return; try { await api.deleteAudience(audience.id); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete audience') } }} aria-label="Delete audience"><Trash2 className="size-4 text-red-500" /></button></div><p className="mt-4 text-[11px] text-slate-500">{audience.members.slice(0, 5).map(item => item.contact.profileName || item.contact.phone).join(' · ')}{audience.members.length > 5 ? ` · +${audience.members.length - 5} more` : ''}</p></article>)}{!audiences.length && <div className="col-span-full rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-xs text-slate-400">No audiences yet</div>}</div>{editing && <AudienceModal audience={editing === true ? undefined : editing} contacts={contacts} close={() => setEditing(null)} saved={async () => { setEditing(null); await refresh() }} />}</div>
}

function AudienceModal({ audience, contacts, close, saved }: { audience?: ApiAudience; contacts: ApiContact[]; close: () => void; saved: () => Promise<void> }) {
  const [name, setName] = useState(audience?.name || ''), [ids, setIds] = useState(audience?.members.map(item => item.contactId) || []), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const submit = async () => { setSaving(true); setError(''); try { const data = { name: name.trim(), contactIds: ids }; audience ? await api.updateAudience(audience.id, data) : await api.createAudience(data); await saved() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save audience'); setSaving(false) } }
  return <div className="overlay"><div className="modal max-h-[90vh] overflow-auto"><div className="modal-head"><div><h2>{audience ? 'Edit audience' : 'Create audience'}</h2><p>Choose contacts already saved in your database.</p></div><button onClick={close}>×</button></div><label>Audience name<input value={name} onChange={e => setName(e.target.value)} placeholder="Appointment reminders" /></label><ContactPicker contacts={contacts} selected={ids} change={setIds} />{error && <p className="template-error">{error}</p>}<div className="modal-actions"><button onClick={close}>Cancel</button><button className="new-template" disabled={saving || !name.trim() || !ids.length} onClick={submit}>{saving ? 'Saving…' : 'Save audience'}</button></div></div></div>
}
export { ContactPicker }
